<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $inspection->label }} — {{ $site->name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        h2 { font-size: 14px; margin: 24px 0 8px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        .meta { color: #555; font-size: 11px; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top; }
        th { background: #f5f5f5; width: 55%; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
        .pass { background: #d1fae5; color: #065f46; }
        .fail { background: #fee2e2; color: #991b1b; }
        .na { background: #e5e7eb; color: #374151; }
        .summary { background: #f9fafb; border: 1px solid #e5e7eb; padding: 12px; border-radius: 4px; }
        .photo-grid { margin-top: 12px; }
        .photo { display: inline-block; width: 48%; margin: 0 1% 12px 0; vertical-align: top; page-break-inside: avoid; }
        .photo img { max-width: 100%; height: auto; border: 1px solid #ddd; }
        .photo p { font-size: 10px; color: #555; margin: 4px 0 0; }
        .footer { margin-top: 30px; font-size: 10px; color: #888; border-top: 1px solid #eee; padding-top: 8px; }
    </style>
</head>
<body>
    <h1>{{ $inspection->label }}</h1>
    <div class="meta">
        <strong>{{ $site->name }}</strong>
        @if($site->full_address)<br>{{ $site->full_address }}@endif
        <br>Inspector: {{ $inspector->name }}
        <br>Completed: {{ $inspection->completed_at?->format('j M Y H:i') ?? now()->format('j M Y H:i') }}
        @if($company)<br>{{ $company->name }}@endif
    </div>

    @if($inspection->summary)
        <h2>Summary</h2>
        <div class="summary">{{ $inspection->summary }}</div>
    @endif

    <h2>Checklist</h2>
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Result</th>
            </tr>
        </thead>
        <tbody>
            @foreach($items as $item)
                @if(($item['type'] ?? '') === 'photos')
                    @continue
                @endif
                @php
                    $value = $responses[$item['key']] ?? '—';
                    $badgeClass = match($value) {
                        'pass' => 'pass',
                        'fail' => 'fail',
                        'na' => 'na',
                        default => '',
                    };
                @endphp
                <tr>
                    <td>{{ $item['label'] }}</td>
                    <td>
                        @if(in_array($value, ['pass', 'fail', 'na']))
                            <span class="badge {{ $badgeClass }}">{{ strtoupper($value) }}</span>
                        @else
                            {{ $value }}
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    @if($photos->where('base64')->count())
        <h2>Photos</h2>
        <div class="photo-grid">
            @foreach($photos as $photo)
                @if($photo['base64'])
                    <div class="photo">
                        <img src="{{ $photo['base64'] }}" alt="">
                        <p>{{ $photo['caption'] }}</p>
                    </div>
                @endif
            @endforeach
        </div>
    @endif

    <div class="footer">
        Generated by ZapTask · Inspection #{{ $inspection->id }}
    </div>
</body>
</html>
