<?php

return [
    'default' => 'general',

    'list' => [
        'general' => 'General / Other',
        'estate-agents' => 'Estate agents',
        'property-management' => 'Property management',
        'construction' => 'Construction',
        'electricians' => 'Electricians',
        'plumbers' => 'Plumbers',
        'cleaning-companies' => 'Cleaning companies',
        'roofers' => 'Roofers',
        'landscapers' => 'Landscapers',
        'facilities-management' => 'Facilities management',
        'care-agencies' => 'Care agencies',
        'restaurants' => 'Restaurants',
        'hotels' => 'Hotels',
        'retail' => 'Retail',
        'marketing-agencies' => 'Marketing agencies',
        'software-development' => 'Software development',
        'accountants' => 'Accountants',
        'recruitment' => 'Recruitment',
        'schools' => 'Schools',
        'charities' => 'Charities',
        'manufacturing' => 'Manufacturing',
    ],

    /*
    | Master todo type definitions (icon = Lucide icon name for the frontend).
    */
    'types' => [
        'Bug' => ['icon' => 'Bug'],
        'Feature' => ['icon' => 'Zap'],
        'Task' => ['icon' => 'CheckSquare'],
        'Story' => ['icon' => 'BookOpen'],
        'Epic' => ['icon' => 'Layers'],
        'Property' => ['icon' => 'Home'],
        'Lead' => ['icon' => 'UserPlus'],
        'Viewing' => ['icon' => 'Eye'],
        'Offer' => ['icon' => 'HandCoins'],
        'Maintenance' => ['icon' => 'Wrench'],
        'Compliance' => ['icon' => 'ShieldCheck'],
        'Tenant' => ['icon' => 'Users'],
        'Inspection' => ['icon' => 'ClipboardCheck'],
        'Lease' => ['icon' => 'FileText'],
        'Site Visit' => ['icon' => 'MapPin'],
        'Snagging' => ['icon' => 'Hammer'],
        'Safety' => ['icon' => 'AlertTriangle'],
        'Material' => ['icon' => 'Package'],
        'Subcontractor' => ['icon' => 'HardHat'],
        'Job' => ['icon' => 'Briefcase'],
        'Quote' => ['icon' => 'FileText'],
        'Install' => ['icon' => 'Wrench'],
        'Repair' => ['icon' => 'Hammer'],
        'Emergency' => ['icon' => 'AlertTriangle'],
        'Deep Clean' => ['icon' => 'Sparkles'],
        'Regular Clean' => ['icon' => 'Sparkles'],
        'Supply' => ['icon' => 'Package'],
        'Survey' => ['icon' => 'ClipboardList'],
        'Warranty' => ['icon' => 'ShieldCheck'],
        'Design' => ['icon' => 'PenTool'],
        'Seasonal' => ['icon' => 'TreePine'],
        'Work Order' => ['icon' => 'ClipboardList'],
        'Vendor' => ['icon' => 'Truck'],
        'Client' => ['icon' => 'User'],
        'Visit' => ['icon' => 'MapPin'],
        'Assessment' => ['icon' => 'ClipboardCheck'],
        'Medication' => ['icon' => 'Pill'],
        'Training' => ['icon' => 'GraduationCap'],
        'Prep' => ['icon' => 'ChefHat'],
        'Service' => ['icon' => 'ConciergeBell'],
        'Stock' => ['icon' => 'Package'],
        'Guest Request' => ['icon' => 'ConciergeBell'],
        'Housekeeping' => ['icon' => 'Sparkles'],
        'Event' => ['icon' => 'Calendar'],
        'Display' => ['icon' => 'LayoutGrid'],
        'Customer' => ['icon' => 'User'],
        'Delivery' => ['icon' => 'Truck'],
        'Campaign' => ['icon' => 'Megaphone'],
        'Creative' => ['icon' => 'Palette'],
        'Content' => ['icon' => 'FileText'],
        'Analytics' => ['icon' => 'BarChart3'],
        'Meeting' => ['icon' => 'Users'],
        'Tax' => ['icon' => 'Calculator'],
        'Audit' => ['icon' => 'Search'],
        'Bookkeeping' => ['icon' => 'BookOpen'],
        'Candidate' => ['icon' => 'UserPlus'],
        'Interview' => ['icon' => 'Calendar'],
        'Placement' => ['icon' => 'CheckCircle'],
        'Admin' => ['icon' => 'ClipboardList'],
        'Lesson' => ['icon' => 'BookOpen'],
        'Student' => ['icon' => 'GraduationCap'],
        'Parent' => ['icon' => 'Users'],
        'Fundraising' => ['icon' => 'Heart'],
        'Volunteer' => ['icon' => 'HeartHandshake'],
        'Production' => ['icon' => 'Factory'],
        'Quality' => ['icon' => 'ShieldCheck'],
        'Order' => ['icon' => 'ShoppingCart'],
        'Inventory' => ['icon' => 'Package'],
        'Project' => ['icon' => 'FolderKanban'],
        'Follow-up' => ['icon' => 'Phone'],
        'Other' => ['icon' => 'CircleHelp'],
    ],

    'industry_types' => [
        'general' => ['Task', 'Project', 'Meeting', 'Follow-up', 'Other'],
        'estate-agents' => ['Property', 'Lead', 'Viewing', 'Offer', 'Maintenance', 'Other'],
        'property-management' => ['Property', 'Tenant', 'Maintenance', 'Inspection', 'Compliance', 'Lease', 'Other'],
        'construction' => ['Site Visit', 'Task', 'Snagging', 'Safety', 'Material', 'Subcontractor', 'Other'],
        'electricians' => ['Job', 'Quote', 'Install', 'Repair', 'Inspection', 'Emergency', 'Other'],
        'plumbers' => ['Job', 'Quote', 'Install', 'Repair', 'Inspection', 'Emergency', 'Other'],
        'cleaning-companies' => ['Job', 'Quote', 'Deep Clean', 'Regular Clean', 'Inspection', 'Supply', 'Other'],
        'roofers' => ['Job', 'Quote', 'Survey', 'Install', 'Repair', 'Warranty', 'Other'],
        'landscapers' => ['Job', 'Quote', 'Design', 'Install', 'Maintenance', 'Seasonal', 'Other'],
        'facilities-management' => ['Work Order', 'Inspection', 'Maintenance', 'Compliance', 'Vendor', 'Emergency', 'Other'],
        'care-agencies' => ['Client', 'Visit', 'Assessment', 'Medication', 'Compliance', 'Training', 'Other'],
        'restaurants' => ['Task', 'Prep', 'Service', 'Stock', 'Maintenance', 'Compliance', 'Other'],
        'hotels' => ['Task', 'Guest Request', 'Housekeeping', 'Maintenance', 'Event', 'Compliance', 'Other'],
        'retail' => ['Task', 'Stock', 'Display', 'Customer', 'Delivery', 'Maintenance', 'Other'],
        'marketing-agencies' => ['Campaign', 'Creative', 'Client', 'Content', 'Analytics', 'Meeting', 'Other'],
        'software-development' => ['Bug', 'Feature', 'Task', 'Story', 'Epic', 'Other'],
        'accountants' => ['Client', 'Tax', 'Audit', 'Bookkeeping', 'Compliance', 'Meeting', 'Other'],
        'recruitment' => ['Candidate', 'Client', 'Interview', 'Placement', 'Compliance', 'Admin', 'Other'],
        'schools' => ['Lesson', 'Admin', 'Student', 'Parent', 'Event', 'Compliance', 'Other'],
        'charities' => ['Campaign', 'Fundraising', 'Volunteer', 'Event', 'Admin', 'Compliance', 'Other'],
        'manufacturing' => ['Production', 'Quality', 'Maintenance', 'Order', 'Safety', 'Inventory', 'Other'],
    ],
];
